### ISSUE TITLE
Something quite interesting happens when you load a custom playermodel in development version.

### ISSUE THREAD

**Issue by SniperGoth** [red-eclipse/world#10]
I have this "vrman" model im using for learning how to animate stuff on tess's engine, more specifically, on NF (still in planning stages, using placeholders) *   .

![2017-11-16_22 21 25_fog_test_edit](https://user-images.githubusercontent.com/24359960/34255619-ad8d4fea-e638-11e7-9326-01928eb5fd06.png)
![2017-12-21_10 27 03_collision_tests_edit](https://user-images.githubusercontent.com/24359960/34255806-874eb0c0-e639-11e7-82ce-2cd81e0b5aef.png)

So, i decided to test it on the RE master. 
And the results.... well.

![20171221102926](https://user-images.githubusercontent.com/24359960/34255899-e15ea03e-e639-11e7-8448-8e7f698d750b.png)
He doesn't show up (not a problem, really, as i am using the same method of configuration from tess)
And since the master is glitchy, since it doesn't have a propper model to glue it's tags, the game just decides to stick the tag_weapon onto the Spawn point, giving some... bizarre  results.
![20171219233622](https://user-images.githubusercontent.com/24359960/34255973-2cddc3dc-e63a-11e7-9098-e236bf9d1899.png)
*bots shooting from the sky, even though they are on the ground.

A video demonstrating the effect for those interested : 

https://youtu.be/L0tH-6_LHvM

**Comment by qreeves** [comment]
LOL, yeah, I made the tags non-optional 😝

**Comment by Dziq84** [comment]
great mountain model I see here

**Comment by qreeves** [comment]
This should be resolved as of red-eclipse/base@6e1e0e9
