### ISSUE TITLE
alarm_light mapmodel

### ISSUE THREAD

**Issue by Dziq84** [red-eclipse/world#23]
I created it lately, I think it will be a waste not having this in game :)  
What do you people think about that

<a href="https://imgur.com/HjqnbIm"><img src="https://i.imgur.com/HjqnbIm.gif" title="source: imgur.com" /></a>

**Comment by IceflowRE** [comment]
Give me! :D

**Comment by SniperGoth** [comment]
So you discovered how to fix the alpha texture issue, or is that still geometry where the light beams pass through?

**Comment by Dziq84** [comment]
its texture with alpha, also rotating thing inside is flat, without thickness. As always I try to use as less polygons as possible

**Comment by qreeves** [comment]
>why WIP laber? ;p it's finished model

There's no file, link, or issue created on base to include it in the game?

**Comment by Dziq84** [comment]
I can include this in RE/dziq if you allow

**Comment by qreeves** [comment]
Yeah, go for it.

**Comment by Dziq84** [comment]
done
