### ISSUE TITLE
LOD (Level Of Detail) system implementation?

### ISSUE THREAD

**Issue by SniperGoth** [red-eclipse/world#3]
Since the game now actually supports propper collision (mdltricollide) and rendering by using tesseract's engine, i'd think we would need a LOD system in place, if one decides to go the static-mesh way of map creation.
Basically, the further away you are of a object, the engine loads a lower-poly version of it, to help performance, as you wouldn't want various 2000 tri models being displayed in the distance.
We could have 3 or 4 slots to it.
How it could work : 

mdllod 1  "mesh.obj"  (highest density model) ~~0-50 m+
mdllod 2  "mesh2.obj" (medium density model) ~~50-100 m+
mdllod 3  "mesh3.obj" (low density model) ~~250 m+
mdllod 4  "mesh4.obj" (lowest density model, loaded on the distance)  ~~500 m +

This could be useful. as of right now, let's say you have made a detailed model, but it still displays on any distance, close or long, so you need to carefully consider where to place it.

**Comment by lsalzman** [comment]
No

**Comment by Dziq84** [comment]
just no?  nice.. its hard to live with that when only one guy who can do that say just 'no',  its hard to implement or what?

**Comment by ThomasMonroe314** [comment]
Something like that would allow for more complex effects to be implemented without compromising the FPS much

**Comment by Dziq84** [comment]
true, we have animated models so I dont think it would be hard to replace one mesh with another in realtime, Now 3D artist are stick to low poly models like in '99 year ;p  I dont know details why just 'no', but please keep in mind that we deserve a answer ;)

**Comment by graphitemaster** [comment]
LOD levels are hard to do right while still being correct looking, it's actually not a matter of just switching to a different model based on distance. Consider the behavior of hitscan against model in the distance (shots don't register against hitbox but rather the actual model in some cases). Consider what needs to be done for iron sights / zoom behavior (you're still far away but the model needs to be highres if you're focusing on it.) Skeletal animation breaks down (skinning in particular) against lower resolution meshes, you actually need a complete seperate rig in some cases with more bones.

**Comment by Dziq84** [comment]
thats an answer! ^^.  
maybe is there a hope that someday LOD will be implemented, even for simple mapmodels

**Comment by acerspyro** [comment]
See https://github.com/red-eclipse/world/issues/8#issuecomment-354027961

**Comment by Dziq84** [comment]
If this is going to be replacement for normal forums, then discussions should never be closed like that. just my 3 cents
