### ISSUE TITLE
how to solve this error

### ISSUE THREAD

**Issue by Arun-Mo** [red-eclipse/world#31]
C:\Program Files (x86)\Python 3.5\Scripts>pip3.5 install --user re2
Collecting re2
  Using cached re2-0.2.22.tar.gz
Installing collected packages: re2
  Running setup.py install for re2 ... error
    Complete output from command "c:\program files (x86)\python 3.5\python.exe"
-u -c "import setuptools, tokenize;__file__='C:\\Users\\ARUN\\AppData\\Local\\Te
mp\\pip-build-_a3cj_hk\\re2\\setup.py';f=getattr(tokenize, 'open', open)(__file_
_);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'e
xec'))" install --record C:\Users\ARUN\AppData\Local\Temp\pip-1zpb2oqg-record\in
stall-record.txt --single-version-externally-managed --compile --user --prefix=:

    running install
    running build
    running build_ext
    building 're2' extension
    error: [WinError 2] The system cannot find the file specified

    ----------------------------------------
Command ""c:\program files (x86)\python 3.5\python.exe" -u -c "import setuptools
, tokenize;__file__='C:\\Users\\ARUN\\AppData\\Local\\Temp\\pip-build-_a3cj_hk\\
re2\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace
('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record
 C:\Users\ARUN\AppData\Local\Temp\pip-1zpb2oqg-record\install-record.txt --singl
e-version-externally-managed --compile --user --prefix=" failed with error code
1 in C:\Users\ARUN\AppData\Local\Temp\pip-build-_a3cj_hk\re2\

**Comment by shacknetisp** [comment]
This is the wrong place to get help for this, red-eclipse/world is about the [arena shooter game](https://redeclipse.net), it's not the re2 wrapper library.

You should file your issues on re2's own github page: https://github.com/axiak/pyre2/issues

**Comment by acerspyro** [comment]
So where in your text did you ask a question
