### ISSUE TITLE
Meeting around the FOSDEM

### ISSUE THREAD

**Issue by IceflowRE** [red-eclipse/world#38]
Maybe you heard about the [FOSDEM](https://fosdem.org/2018/), it is a free event for software developers to meet, share ideas and collaborate. It will be at the 3/4 february 2018 in Brussels.

Some people of the community will be there, so it could be a chance to meet each other in real life. To discuss where and when to meet you could write maybe times here or join our [Discord Community Server](https://discord.gg/FHsqtF7), this would also be the prefered way to communicate if we are there. (i dont mean we arent talking ...)

Iam around at saturday between 10 and 17, but i will visit some presentations as well.

**Comment by Sixardyh** [comment]
I will also be around for most of the day Saturday and Sunday. I will spend most of my time assisting to talks, though.

**Comment by IceflowRE** [comment]
Event is over.
