### ISSUE TITLE
Enter commands in server console

### ISSUE THREAD

**Issue by Goldenbrain1** [red-eclipse/world#45]
I had an idea for improving the server console interface.
It is to make a command line for entering command in the server, like in minecraft.
It would be useful to moderate without connecting or to talk to the players.
I don't really know how is red eclipse coded, so ill need help to do that.

**Comment by qreeves** [comment]
The problem with such a thing is that you usually need to make use of a library which handles such things. The standard output/input is very rudimentary. Yes, it could be done, but probably requires a different approach on each platform unless a cross platform library is used. Adding libraries isn't something we like to do in an effort to keep things simple.

That being said, I have been thinking about a remote command input terminal (not just for servers, but for administering the master server as well). This could be paired with a small program (eg. `redeclipse-cli`) that just interfaces with that and provides an command line like interface. This way, it'd be easy to write a similar console inside the game itself as well.

**Comment by JeffBobbo** [comment]
In running Minecraft servers, I've found that the ability to perform commands on STDIN one of the worst things ever. It makes daemonizing the process super annoying, as you have to wrap it in screen, nohup, or similar. If you don't get it right, it also spams STDOUT with ">", making the log file useless.

A remote console (also like in Minecraft), which would allow a user to connect (probably with their auth handle and key) is a far better approach, although could potentially be a lot of work.

**Comment by Goldenbrain1** [comment]
Ok i'll maybe try to do an external console but i need to know how red eclipse (and the red eclipse server) is coded.
Maybe is there a tutorial I missed ?

**Comment by qreeves** [comment]
We don't really provide documentation on how to modify the code as we are a game project, not an engine/API, so it is assumed you have at least some level of competency with C++.

That being said, if you'd like us to implement it it, I approve this as a feature request and you can [create an issue](https://github.com/red-eclipse/base/issues/new) in our base repository.

**Comment by Goldenbrain1** [comment]
Ok thank you, but i only know C, not C++, is it very different ?
Anyway I'm going to train a bit and look at the source code before creating issue
