### ISSUE TITLE
Crosshair health color improvements

### ISSUE THREAD

**Issue by Calinou** [red-eclipse/world#46]
The current crosshair health indication pulses the crosshair into a red color when the player's health is low. It has a few downsides:

- It requires the crosshair to pulse at least once for the player to notice their health is low; this is problematic in a fast-paced shooter.
- It does not accurately tell the player about their health status when their health is above 100.

Based on a pull request I submitted to another open source game (https://github.com/jdolan/quetoo/pull/536), I suggest replacing the color pulsing with a static color change based on the player health:

- health ⩽ 15: red
- 15 ⩽ health ⩽ 65: fade from red to yellow
- 65 ⩽ health ⩽ 100: fade from yellow to white
- health ⩽ 150: fade from white to green

Those values are valid for `playerhealth 100` and `maxhealth 1.5`; these would be adjusted if those variables are modified.

Variables could be added to disable fading into green with health values above 100, or turn the white-yellow-red fade into a simpler white-red one.

**Comment by IceflowRE** [comment]
And an option to turn this totally off an d use one color at all.

**Comment by qreeves** [comment]
I was actually thinking about removing it altogether due to the fact it interferes with the crosshair. So I'm wondering if we should change the colour of it at all, or if we should find a new method?

**Comment by Calinou** [comment]
> So I'm wondering if we should change the colour of it at all, or if we should find a new method?

I find that changing the crosshair color is an intuitive way to know one's health without checking the bottom-left corner of the HUD, so I would really miss that feature.

**Comment by qreeves** [comment]
OK no worries, two people seem to like the idea 😄
