### ISSUE TITLE
Custom mapmodels crash the game

### ISSUE THREAD

**Issue by JEmanuel1806** [red-eclipse/world#49]
As i started including custom mapmodels to my map, i soon noticed that some models lead my map to crash. It especially occurs as soon as i start shooting the mapmodel or sometimes even just touch it. 

Now my question is if this is a problem of either my lap (have to work on a "weak" laptop at the moment), the game itself or the mapmodel.
I usually use OBJ files (not more than 3 MB space) for the models and place them in seperate folders along with the Obj.cfg and the tex+bump.

Example:

      objload model.obj    // load an exported mesh

      objskin * tex.jpg     // this will assign an image diffuse texture to an loaded mesh
      objbumpmap *NormalMap.jpg    //the same as above but assign a normalmap texture

      objspec * 30    //  value of specular highlights that model reflects during game (100 is default, can be higher, 0 means no spec)
      mdlscale 400    // default RE scale, change this if model need to be bigger or smaller by default
      mdlglare 0.4    // tweaking this might be important to properly display a model in game, this affects how strong glare will be seen 

Are there only specific mapmodel types allowed ? Or maybe its a problem with the scaling, i dont know.

Thanks

**Comment by SniperGoth** [comment]
I've known this to happen to higher poly models, sometimes, from my experience on tess editing.
Depending on the case, if you "enter" it by accident, it also crashes.
But this is quite a rare occurence, so... i don't know how to replicate it here atm.
As for this happening within RE itself, that's a first.

**Comment by JEmanuel1806** [comment]
yea, i usually use low poly models with low bytes because ,as you said , high poly crashes it. But the problem is , all the "standard " mapmodels also work without problem so i don't see the problem with the custom ones. As soon as I shoot it , the game freezes, otherwise nothing happens.

**Comment by Dziq84** [comment]
how many tris have this crashing mesh? maybe this one need a collision mesh applied?

**Comment by Dziq84** [comment]
how many tris have this crashing mesh? maybe this one need a collision mesh applied?

**Comment by qreeves** [comment]
Can't do much without a backtrace, crash needs to be reproduced in a debugger.

**Comment by qreeves** [comment]
Sorry, I wrote the previous comment in a bit of a rush. I should have said: _Can you provide the files in question so it can be tested in a debugger?_ This is how we generate a backtrace if you are unable to.

**Comment by JEmanuel1806** [comment]
No Problem at all

![errors](https://user-images.githubusercontent.com/33660472/37709345-3d266296-2d0a-11e8-88f7-b6d4ec56993d.PNG)
![error](https://user-images.githubusercontent.com/33660472/37709346-3d48be68-2d0a-11e8-9f41-4cd9cf9724fa.PNG)

 , just wasn't able to answer yet. Okay , so what exactly do you need? I ran the game in the Debugger of CodeBlocks and got this (tried it two times). Don't know if it helps.

If you need something else, just say it, I'll try to send it. 

Thank you very much.

**Comment by qreeves** [comment]
Oh, I'm guessing this is with the current stable release, v1.6?

**Comment by JEmanuel1806** [comment]
yes, that is correct.

**Comment by qreeves** [comment]
Yeah, I can't be sure if that's even an issue in the development version as a lot of it has been rewritten. Are you able to test with the dev version or provide one of the files that causes the crash?

**Comment by JEmanuel1806** [comment]
sure thing , I'll try. Gonna upload it later on.

**Comment by JEmanuel1806** [comment]
Oh by the way  which file do you need? Do you mean the mapmodel that crashes the game ?

**Comment by qreeves** [comment]
Yes, the model and the config file for it you're using.

**Comment by JEmanuel1806** [comment]
[mapmodels.zip](https://github.com/red-eclipse/world/files/1837687/mapmodels.zip)

those are two obj. models which crash the game

**Comment by lsalzman** [comment]
Fixed now.

**Comment by qreeves** [comment]
Backported to stable, so just update to fix it.

**Comment by IceflowRE** [comment]
What was the problem here?

**Comment by JEmanuel1806** [comment]
thanks guys

**Comment by qreeves** [comment]
https://github.com/red-eclipse/base/compare/3cbdb60d332d...11f6336fe283
