### ISSUE TITLE
Flag/bomb glitches

### ISSUE THREAD

**Issue by brian70123475** [red-eclipse/world#61]
Has anyone else noticed that the F key doesn't do anything when trying to interact with a flag or a bomber-ball?

Just wanted to make sure that it's not something I missed before I embarrass myself with a false issue.

I did try temporarily renaming my config.cfg.

**Comment by brian70123475** [comment]
> I don't think there's any modes where you *can't* pick them up.

Walking over a bomber ball or the enemy team's flag works flawlessly. Picking up your own flag, throwing away a flag that you're holding, or throwing away a bomber ball that you're holding, are the things that I can't do -- in other words, everything that requires the F key.

**Comment by Dziq84** [comment]
I can confirm this in master-2120,  interacting with own flag/ throwing bomb don't working here
Bind is displayed: "Press F to .."  and it does nothing.
Just tested with bomber and standard CTF

**Comment by qreeves** [comment]
Oh, is it the same in the stable version?

**Comment by brian70123475** [comment]
Well, whatever it is, it seems to be gone in the latest update(s).

**Comment by qreeves** [comment]
Oh yep, sorry, fixed it yesterday and forgot to mention it here. Thanks for the report though!
