### ISSUE TITLE
Install RE 1.6.0 with tar.bz2 on fedora 25

### ISSUE THREAD

**Issue by ghost** [red-eclipse/world#62]
Hi! I have redeclipse as appimage but I  want to get it in tar.bz2 (bugs etc...). I read the wiki but The game doesn't work. I must have a solution without administrator password. Can anyone help me?

**Comment by qreeves** [comment]
You shouldn't need an administrator password at all with the tarball extracted into your personal home directory. You say the game doesn't work, but we need more information than that.

- What steps are you taking to download, extract, and run?
- What are the contents of the screen output when you try to run it?

**Comment by Zorglub23** [comment]
The game doesn't because it don't launch it. I extracted the files but when I try to run it, it doesn't launch the game. My screen is 16:9. I tryed to install curl and git but I need an admin password.

**Comment by qreeves** [comment]
Ah I see. Edit `branch.txt` and replace the word "stable" with "inplace".

**Comment by Zorglub23** [comment]
OK thanks! I will try. And I want to say, your game is the best FPS ever =)!

**Comment by qreeves** [comment]
No problem, have fun!

**Comment by Zorglub23** [comment]
Sry but it doesn't work =|. I don't know why.

**Comment by Zorglub23** [comment]
To be more precise, it launch "start the app" but I don't see the game when I make Alt-Tab.

**Comment by qreeves** [comment]
I'll need to see the contents of the screen output to know what's going on then. Can you copy/paste here?

**Comment by Zorglub23** [comment]
pixel size :0.248mm , resolution:1920x1080, 

Design | ultra slim
-- | --
Diagonal | 21.5", 54.7cm
Panel | AH-IPS LED, matte finish
Native resolution | 1920 x 1080 (2.1 megapixel Full HD)
Aspect ratio | 16:9
Brightness | 250 cd/m² typical
Static contrast | 1000:1 typical
Advanced contrast | 5M:1
Response time | 4ms
Viewing zone | horizontal/vertical: 178°/178°, right/left: 89°/89°, up/down: 89°/89°
Colour support | 16.7mln 8bit (6bit + Hi-FRC)
Horizontal Sync | 24 - 80KHz
Vertical Sync | 56 - 75Hz
Viewable area W x H | 476.1 x 267.8mm, 18.7 x 10.5"
Pixel pitch | 0.248mm
Colour | matte, black

Signal input | VGA x1DVI x1HDMI x1
-- | --
HDCP | yes

**Comment by Zorglub23** [comment]
I use gnome. When I launch it in a terminal, it says 

> "No such or file directory"

**Comment by qreeves** [comment]
You need to run the "redeclipse.sh" file from within the folder you extracted Red Eclipse to. It should go like this:
```
tar -jxvf redeclipse_1.6.0_nix.tar.gz
cd redeclipse-1.6.0
./redeclipse.sh
```
If it won't execute:
```
chmod +x redeclipse.sh
./redeclipse.sh
```
Please note the `./` before the script name, that tells it to execute the file (because it isn't in $PATH).

**Comment by Zorglub23** [comment]
Thanks. But I know that there is ./ before the file but it always says "no such file or directory". Maybe a prob with my computer...

**Comment by qreeves** [comment]
It just sounds like you're not in the right directory. Is that the only output?

**Comment by Zorglub23** [comment]
Hi! I found the prob! It is required dependances. Lds2maker I think. A firend  had the same prob. Thanks for your help!

**Comment by qreeves** [comment]
Closing due to being marked as solved. If you still require help please feel free to open a new request.
