### ISSUE TITLE
Hello Chaps spot of help?

### ISSUE THREAD

**Issue by Santa-lil-baby-jesus** [red-eclipse/world#76]
Hello I'm Santa. 
So I've just logged in to geras server and golden one and can't see either the chat messages or the sights for my weapons. Is there an update I dojn't know about? Something I'm not doing?

**Comment by Calinou** [comment]
Perhaps the HUD is hidden for some reason; try pressing T then enter `/showhud 1`.

**Comment by Santa-lil-baby-jesus** [comment]
That's it! Thanks a lot!

**Comment by Calinou** [comment]
Closing, as this seems to be resolved :slightly_smiling_face:
