### ISSUE TITLE
RE won't start due to missing libsteam_api.so

### ISSUE THREAD

**Issue by MirceaKitsune** [red-eclipse/world#82]
The latest Git version of Red Eclipse will no longer start due to a missing libsteam_api.so. I understand Steam support was just recently added, so it's likely an issue caused by that.

`/home/mircea/Games/Cube/Redeclipse_GIT/bin/amd64/redeclipse_linux: error while loading shared libraries: libsteam_api.so: cannot open shared object file: No such file or directory`

Many of us don't have Steam installed, especially not as a system-wide library on Linux systems. The build process should detect that and not ask for Steam dependencies if you're not compiling with the intent to have Steam integration.

**Comment by IceflowRE** [comment]
Another issue we should consider is, not every architecture has the steam libraries.

**Comment by shacknetisp** [comment]
The libraries are included as binaries in the appropriate arch folder.

`redeclipse.sh` uses this: `export LD_LIBRARY_PATH=${REDECLIPSE_PATH}/bin/${REDECLIPSE_ARCH}:${LD_LIBRARY_PATH}`

**Comment by qreeves** [comment]
Yeah, are you using the shell script?

**Comment by MirceaKitsune** [comment]
I should clarify that I built RE just by running the command: `make -C src/ install` Same issue in latest Git master with that.

**Comment by qreeves** [comment]
Yeah, I mean are you running `./redeclipse.sh` or are you running the binary directly?

**Comment by MirceaKitsune** [comment]
I was running the binary file directly. It appears that running redeclipse.sh makes that error go away, RE now launches again. This does however also change my settings directory and such. I'll dig into exactly which bit I need to also get it working the old way (launching the binary manually).

**Comment by qreeves** [comment]
`export LD_LIBRARY_PATH="${REDECLIPSE_PATH}/bin/${REDECLIPSE_ARCH}:${LD_LIBRARY_PATH}"`

**Comment by MirceaKitsune** [comment]
Confirming that this fixed it. If it's normal for the binary to look for external libraries in the default build, this solution is fine in my book.
