### ISSUE TITLE
Which software is used for making the game models?

### ISSUE THREAD

**Issue by proneon267** [red-eclipse/world#87]
I wanted to know which software is used for making the game models like the characters, weapons and environments? Blender?

**Comment by Goldenbrain1** [comment]
well, most of the models are iqm, and there are scripts to convert blender files or most model types to iqm.

**Comment by proneon267** [comment]
is iqm - Inter quake model? Also can the blender files be converted to iqm? I mean are there scripts for that?

**Comment by Goldenbrain1** [comment]
Yes it's Inter quake model, and yes there are scripts to convert to iqm directly from blender ( https://github.com/lsalzman/iqm )

**Comment by proneon267** [comment]
Thanks! I will mark this topic as close :)
