### ISSUE TITLE
guys we need to talk ;D

### ISSUE THREAD

**Issue by eaeaivjmga88** [red-eclipse/world#99]
okay guys i took the cartoon to polish the pilot. gonna try again but first things have come to mind, quinn buddy amigo ;D i've been here for over a year and i know the promblems of red eclipse now some people here are not my freinds u know, some distinctively evil which i would not name but that is not the reason i'm posting this. you see i been thinking about red eclipse future and believe i shown the cartoon to a lot of people and they gave me praise and tell me good things. and i'm glad now i'm learning to use blender downlaoded and all. people tell me that making cartoons is gonna make a lot of money for u guys ;D. and i'm glad going to continue with another post.

**Comment by eaeaivjmga88** [comment]
and i'm happy u guys are gonna recieve a lot of money and players i'm working about it, but i know the reality once red eclipse makes 2,000 or makes 10,000 dollars a month or more someday you guys are gonna feel releif. but i know life and life gives u promblems and troubles and i'm here about talking about those things. beleive me, i have experience in life with promblems business promblems, family promblems, and all the promblems life throws it happens ;D. and if we start talking about those things we prepare for the future and good things happen. so now breaking it down and i continue with the post

**Comment by eaeaivjmga88** [comment]
lets agree between us that if money comes in by the laods there will be no in fighting with us, all agree to work as a team. quinn this is between me, quinn, dziq, molex, beha, and snipergoth u guys have experience with this and take it responsible. i'm going to be selfless in this so u can see a comitment and integrity by my part. i don't want to recieve money, nope. i'll show my selfless act so u can see my model of making things work and nothing about petty fights. were all adults here and i know quinn is an okay guy, snipergoth is okay, molex is okay but there is evil sometimes in red eclipse and sometimes i know ther will be discussion among us. continue with another post

**Comment by eaeaivjmga88** [comment]
and other people inside red eclipse are gonna get angry and people would want more money and then everyone fights each other. things happen like that in businesses and u know what that ruins the business. people get one agaisnt each other. serious now red eclipse does not need those things i'm sure u guys have already had those promblems but things happen like that. above all money makes that happen. now i'm not gonna back down with the project i know how to go around things to make it work. my commitment and genius tell me how to make things work and let people who enjoy red eclipse keep having the game and enjoy it. i know some will say nothing is gonna happen and i'm exxagerating i'm continuing with another post

**Comment by eaeaivjmga88** [comment]
but it's better to prevent and discuss this so things can go ahead and succeed . and becuase we talk about all chances about those things happening will dimnish. and new projects will arise for u guys. i'm just a good angel watching over ya. so express your opinion so anything that could happen in the future disappears ;D. i'm continuing with the artwork cya .

**Comment by SniperGoth** [comment]
Good luck with it, is all i can say...

**Comment by Dziq84** [comment]
not nice to write many consecutive posts each under another ... use EDIT function next time please!
and nobody is interested in your stupid cartoon with 1/10 quality, gg - bb
